# Generated by Django 5.1.5 on 2025-04-22 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='anuncios/')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('enlace', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField()),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('destacado', models.BooleanField(default=False)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('lugar', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('destacado', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('fuente', models.CharField(blank=True, max_length=255, null=True)),
                ('vistas', models.IntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comentarios_habilitados', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='noticias.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=255)),
                ('fecha_publicado', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='noticias.noticia')),
            ],
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.CharField(max_length=255)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('contenido', models.TextField()),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='entrevistas/')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('periodista', models.CharField(max_length=255)),
                ('destacado', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, to='noticias.tag')),
            ],
        ),
    ]
