# Generated by Django 5.1.5 on 2025-06-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='organizacion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
