# Generated by Django 5.1.5 on 2025-04-22 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
    ]
