# Generated by Django 5.1.5 on 2025-08-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_evento_direccion_evento_organizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=50)),
                ('apellido_contacto', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=11)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FranjaSuperior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=500)),
            ],
        ),
    ]
