# Generated by Django 5.1.5 on 2025-04-22 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20250421_2202'),
    ]

    operations = [
    ]
