# Generated by Django 5.1.5 on 2025-04-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_anuncio_slug_entrevista_slug_evento_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
