# Generated by Django 5.1.5 on 2025-08-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_alter_contacto_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
