# Generated by Django 5.1.5 on 2025-08-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_alter_contacto_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='franjasuperior',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
