# Generated by Django 5.1.5 on 2026-03-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_franjasuperior_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevista',
            name='vistas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evento',
            name='tags',
            field=models.ManyToManyField(blank=True, to='noticias.tag'),
        ),
        migrations.AddField(
            model_name='evento',
            name='vistas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
