# Generated by Django 5.1.5 on 2026-03-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0007_entrevista_vistas_evento_tags_evento_vistas'),
    ]

    operations = [
        migrations.AddField(
            model_name='franjasuperior',
            name='vistas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
