# Generated by Django 5.1.5 on 2026-03-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0008_franjasuperior_vistas'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='cta_text',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='ubicacion',
            field=models.CharField(choices=[('home_between_news_events', 'Home entre Noticias y Eventos'), ('home_between_events_interviews', 'Home entre Eventos y Entrevistas'), ('home_after_interviews', 'Home después de Entrevistas')], default='home_between_news_events', max_length=64),
        ),
    ]
