# Generated by Django 5.1.5 on 2026-04-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0011_fechaevento_remove_evento_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechaevento',
            name='fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fechaevento',
            name='inicio',
            field=models.DateField(),
        ),
    ]
