# Generated by Django 5.1.5 on 2026-04-29 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0013_simplificar_fechaevento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fechaevento',
            options={'ordering': ['fecha', 'id'], 'verbose_name': 'Fecha de evento', 'verbose_name_plural': 'Fechas de eventos'},
        ),
        migrations.RemoveField(
            model_name='fechaevento',
            name='orden',
        ),
    ]
