# Generated by Django 5.1.5 on 2026-07-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0014_alter_fechaevento_options_remove_fechaevento_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevista',
            name='cita_destacada',
            field=models.TextField(blank=True, help_text='Cita corta para tarjetas/portadas. No se deriva del contenido.', null=True),
        ),
        migrations.AddField(
            model_name='entrevista',
            name='credito_foto_portada',
            field=models.CharField(blank=True, help_text='Crédito fotográfico de imagen_portada (ej. "Foto: Juan Pérez").', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entrevista',
            name='rol_entrevistado',
            field=models.CharField(blank=True, help_text='Rol o cargo del entrevistado (ej. "DJ y productor").', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fotoentrevista',
            name='credito',
            field=models.CharField(blank=True, help_text='Crédito fotográfico (ej. "Foto: Juan Pérez").', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fotoevento',
            name='credito',
            field=models.CharField(blank=True, help_text='Crédito fotográfico (ej. "Foto: Juan Pérez").', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fotonoticia',
            name='credito',
            field=models.CharField(blank=True, help_text='Crédito fotográfico (ej. "Foto: Juan Pérez").', max_length=255, null=True),
        ),
    ]
