# Generated by Django 5.1.5 on 2026-07-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0015_entrevista_cita_destacada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='ubicacion',
            field=models.CharField(choices=[('home_between_news_events', 'Home entre Noticias y Eventos'), ('home_between_events_interviews', 'Home entre Eventos y Entrevistas'), ('home_after_interviews', 'Home después de Entrevistas'), ('listado_noticias', 'Listado de Noticias'), ('listado_eventos', 'Listado de Eventos'), ('listado_entrevistas', 'Listado de Entrevistas'), ('detalle_noticia', 'Detalle de Noticia'), ('detalle_evento', 'Detalle de Evento'), ('detalle_entrevista', 'Detalle de Entrevista')], default='home_between_news_events', max_length=64),
        ),
    ]
