# Generated by Django 5.1.5 on 2026-07-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0016_alter_anuncio_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.CharField(choices=[('instagram', 'Instagram'), ('whatsapp', 'Comunidad de WhatsApp'), ('spotify', 'Spotify'), ('tiktok', 'TikTok')], max_length=20, unique=True)),
                ('label', models.CharField(help_text='Texto visible del link (ej. "Comunidad de WhatsApp").', max_length=100)),
                ('url', models.URLField()),
                ('contador', models.PositiveIntegerField(blank=True, help_text='Seguidores/miembros a mostrar en el panel de Comunidad. Vacío = no se muestra la cifra.', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Red social',
                'verbose_name_plural': 'Redes sociales',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
