# Generated by Django 5.1.5 on 2025-05-09 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='store_categ_nombre_e8fa22_idx')],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('shipping_address', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, upload_to='productos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('destacado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.categoria')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.producto')),
            ],
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['id', 'slug'], name='store_produ_id_044fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='store_produ_nombre_7a9544_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['creado'], name='store_produ_creado_58e78d_idx'),
        ),
    ]
